import { Body } from "./types";

export const bodies: Body[] = [
    {
        "name": "Standard Kart",
        "speedGround": 0,
        "speedWater": 0,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": 0,
        "weight": 0,
        "handlingGround": 0,
        "handlingWater": 0,
        "handlingAir": 0,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0,
        "insideDrift": false
      },
      {
        "name": "Pipe Frame",
        "speedGround": -0.5,
        "speedWater": 0,
        "speedAir": -0.5,
        "speedGravity": -0.5,
        "acceleration": 0.5,
        "weight": -0.25,
        "handlingGround": 0.5,
        "handlingWater": 0.5,
        "handlingAir": -0.25,
        "handlingGravity": 0.25,
        "grip": 0.25,
        "miniturbo": 0.5,
        "insideDrift": false
      },
      {
        "name": "Mach 8",
        "speedGround": 0,
        "speedWater": 0,
        "speedAir": 0.25,
        "speedGravity": 0.5,
        "acceleration": -0.25,
        "weight": 0.25,
        "handlingGround": -0.25,
        "handlingWater": 0,
        "handlingAir": -0.25,
        "handlingGravity": 0.25,
        "grip": 0.25,
        "miniturbo": 0,
        "insideDrift": false
      },
      {
        "name": "Steel Driver",
        "speedGround": 0.25,
        "speedWater": 0.5,
        "speedAir": -0.75,
        "speedGravity": -0.25,
        "acceleration": -0.75,
        "weight": 0.5,
        "handlingGround": -0.5,
        "handlingWater": 0.75,
        "handlingAir": -0.5,
        "handlingGravity": -0.5,
        "grip": 0,
        "miniturbo": -0.5,
        "insideDrift": false
      },
      {
        "name": "Cat Cruiser",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0.25,
        "speedGravity": 0,
        "acceleration": 0.25,
        "weight": 0,
        "handlingGround": 0.25,
        "handlingWater": 0,
        "handlingAir": 0.25,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0.25,
        "insideDrift": false
      },
      {
        "name": "Circuit Special",
        "speedGround": 0.5,
        "speedWater": -0.5,
        "speedAir": -0.25,
        "speedGravity": 0.25,
        "acceleration": -0.75,
        "weight": 0.25,
        "handlingGround": -0.5,
        "handlingWater": -0.25,
        "handlingAir": -0.75,
        "handlingGravity": -0.25,
        "grip": -0.5,
        "miniturbo": -0.75,
        "insideDrift": false
      },
      {
        "name": "Tri-Speeder",
        "speedGround": 0.25,
        "speedWater": 0.5,
        "speedAir": -0.75,
        "speedGravity": -0.25,
        "acceleration": -0.75,
        "weight": 0.5,
        "handlingGround": -0.5,
        "handlingWater": 0.75,
        "handlingAir": -0.5,
        "handlingGravity": -0.5,
        "grip": 0,
        "miniturbo": -0.5,
        "insideDrift": false
      },
      {
        "name": "Badwagon",
        "speedGround": 0.5,
        "speedWater": -0.25,
        "speedAir": -0.5,
        "speedGravity": 0,
        "acceleration": -1,
        "weight": 0.5,
        "handlingGround": -0.75,
        "handlingWater": -0.25,
        "handlingAir": -0.75,
        "handlingGravity": -0.5,
        "grip": 0.5,
        "miniturbo": -1,
        "insideDrift": false
      },
      {
        "name": "Prancer",
        "speedGround": 0.25,
        "speedWater": 0,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": -0.25,
        "handlingGround": 0,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": -0.25,
        "grip": -0.25,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "Biddybuggy",
        "speedGround": -0.75,
        "speedWater": -0.5,
        "speedAir": -0.5,
        "speedGravity": -0.25,
        "acceleration": 0.75,
        "weight": -0.5,
        "handlingGround": 0.5,
        "handlingWater": 0.5,
        "handlingAir": 0.25,
        "handlingGravity": 0.5,
        "grip": 0.25,
        "miniturbo": 0.75,
        "insideDrift": false
      },
      {
        "name": "Landship",
        "speedGround": -0.5,
        "speedWater": 0.5,
        "speedAir": -0.25,
        "speedGravity": -0.75,
        "acceleration": 0.5,
        "weight": -0.5,
        "handlingGround": 0.25,
        "handlingWater": 0.75,
        "handlingAir": 0,
        "handlingGravity": -0.25,
        "grip": 0.75,
        "miniturbo": 0.5,
        "insideDrift": false
      },
      {
        "name": "Sneeker",
        "speedGround": 0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": 0,
        "handlingGround": 0,
        "handlingWater": 0,
        "handlingAir": -0.25,
        "handlingGravity": 0,
        "grip": -0.75,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "Sports Coupe",
        "speedGround": 0,
        "speedWater": 0,
        "speedAir": 0.25,
        "speedGravity": 0.5,
        "acceleration": -0.25,
        "weight": 0.25,
        "handlingGround": -0.25,
        "handlingWater": 0,
        "handlingAir": -0.25,
        "handlingGravity": 0.25,
        "grip": 0.25,
        "miniturbo": 0,
        "insideDrift": false
      },
      {
        "name": "Gold Standard",
        "speedGround": 0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": 0,
        "handlingGround": 0,
        "handlingWater": 0,
        "handlingAir": -0.25,
        "handlingGravity": 0,
        "grip": -0.75,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "GLA",
        "speedGround": 0.5,
        "speedWater": -0.25,
        "speedAir": -0.5,
        "speedGravity": 0,
        "acceleration": -1,
        "weight": 0.5,
        "handlingGround": -0.75,
        "handlingWater": -0.25,
        "handlingAir": -0.75,
        "handlingGravity": -0.5,
        "grip": 0.5,
        "miniturbo": -1,
        "insideDrift": false
      },
      {
        "name": "W 25 Silver Arrow",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0.25,
        "acceleration": 0.25,
        "weight": -0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": 0.25,
        "grip": 0.5,
        "miniturbo": 0.25,
        "insideDrift": false
      },
      {
        "name": "300 SL Roadster",
        "speedGround": 0,
        "speedWater": 0,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": 0,
        "weight": 0,
        "handlingGround": 0,
        "handlingWater": 0,
        "handlingAir": 0,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0,
        "insideDrift": false
      },
      {
        "name": "Blue Falcon",
        "speedGround": 0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0.25,
        "acceleration": -0.25,
        "weight": -0.5,
        "handlingGround": -0.25,
        "handlingWater": 0.25,
        "handlingAir": -0.5,
        "handlingGravity": 0.5,
        "grip": 0,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "Tanooki Kart",
        "speedGround": -0.25,
        "speedWater": 0.25,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": 0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.5,
        "handlingAir": 0,
        "handlingGravity": 0,
        "grip": 1,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "B Dasher",
        "speedGround": 0.5,
        "speedWater": -0.5,
        "speedAir": -0.25,
        "speedGravity": 0.25,
        "acceleration": -0.75,
        "weight": 0.25,
        "handlingGround": -0.5,
        "handlingWater": -0.25,
        "handlingAir": -0.75,
        "handlingGravity": -0.25,
        "grip": -0.5,
        "miniturbo": -0.75,
        "insideDrift": false
      },
      {
        "name": "Streetle",
        "speedGround": -0.5,
        "speedWater": 0.5,
        "speedAir": -0.25,
        "speedGravity": -0.75,
        "acceleration": 0.5,
        "weight": -0.5,
        "handlingGround": 0.25,
        "handlingWater": 0.75,
        "handlingAir": 0,
        "handlingGravity": -0.25,
        "grip": 0.75,
        "miniturbo": 0.5,
        "insideDrift": false
      },
      {
        "name": "P-Wing",
        "speedGround": 0.5,
        "speedWater": -0.5,
        "speedAir": -0.25,
        "speedGravity": 0.25,
        "acceleration": -0.75,
        "weight": 0.25,
        "handlingGround": -0.5,
        "handlingWater": -0.25,
        "handlingAir": -0.75,
        "handlingGravity": -0.25,
        "grip": -0.5,
        "miniturbo": -0.75,
        "insideDrift": false
      },
      {
        "name": "Koopa Clown",
        "speedGround": -0.25,
        "speedWater": 0.25,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": 0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.5,
        "handlingAir": 0,
        "handlingGravity": 0,
        "grip": 1,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "Standard Bike",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0.25,
        "acceleration": 0.25,
        "weight": -0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": 0.25,
        "grip": 0.5,
        "miniturbo": 0.25,
        "insideDrift": false
      },
      {
        "name": "Comet",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0.25,
        "speedGravity": 0,
        "acceleration": 0.25,
        "weight": 0,
        "handlingGround": 0.25,
        "handlingWater": 0,
        "handlingAir": 0.25,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0.25,
        "insideDrift": true
      },
      {
        "name": "Sport Bike",
        "speedGround": 0.25,
        "speedWater": 0,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": -0.25,
        "handlingGround": 0,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": -0.25,
        "grip": -0.25,
        "miniturbo": -0.25,
        "insideDrift": true
      },
      {
        "name": "The Duke",
        "speedGround": 0,
        "speedWater": 0,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": 0,
        "weight": 0,
        "handlingGround": 0,
        "handlingWater": 0,
        "handlingAir": 0,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0,
        "insideDrift": false
      },
      {
        "name": "Flame Rider",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0.25,
        "acceleration": 0.25,
        "weight": -0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": 0.25,
        "grip": 0.5,
        "miniturbo": 0.25,
        "insideDrift": false
      },
      {
        "name": "Varmint",
        "speedGround": -0.5,
        "speedWater": 0,
        "speedAir": -0.5,
        "speedGravity": -0.5,
        "acceleration": 0.5,
        "weight": -0.25,
        "handlingGround": 0.5,
        "handlingWater": 0.5,
        "handlingAir": -0.25,
        "handlingGravity": 0.25,
        "grip": 0.25,
        "miniturbo": 0.5,
        "insideDrift": false
      },
      {
        "name": "Mr Scooty",
        "speedGround": -0.75,
        "speedWater": -0.5,
        "speedAir": -0.5,
        "speedGravity": -0.25,
        "acceleration": 0.75,
        "weight": -0.5,
        "handlingGround": 0.5,
        "handlingWater": 0.5,
        "handlingAir": 0.25,
        "handlingGravity": 0.5,
        "grip": 0.25,
        "miniturbo": 0.75,
        "insideDrift": false
      },
      {
        "name": "Jet Bike",
        "speedGround": 0.25,
        "speedWater": 0,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": -0.25,
        "handlingGround": 0,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": -0.25,
        "grip": -0.25,
        "miniturbo": -0.25,
        "insideDrift": true
      },
      {
        "name": "Yoshi Bike",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0.25,
        "speedGravity": 0,
        "acceleration": 0.25,
        "weight": 0,
        "handlingGround": 0.25,
        "handlingWater": 0,
        "handlingAir": 0.25,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0.25,
        "insideDrift": true
      },
      {
        "name": "Master Cycle",
        "speedGround": 0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": 0,
        "handlingGround": 0,
        "handlingWater": 0,
        "handlingAir": -0.25,
        "handlingGravity": 0,
        "grip": -0.75,
        "miniturbo": -0.25,
        "insideDrift": true
      },
      {
        "name": "Master Cycle Zero",
        "speedGround": -0.25,
        "speedWater": 0.25,
        "speedAir": 0,
        "speedGravity": 0,
        "acceleration": -0.5,
        "weight": 0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.5,
        "handlingAir": 0,
        "handlingGravity": 0,
        "grip": 1,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "City Tripper",
        "speedGround": -0.5,
        "speedWater": 0,
        "speedAir": -0.5,
        "speedGravity": -0.5,
        "acceleration": 0.5,
        "weight": -0.25,
        "handlingGround": 0.5,
        "handlingWater": 0.5,
        "handlingAir": -0.25,
        "handlingGravity": 0.25,
        "grip": 0.25,
        "miniturbo": 0.5,
        "insideDrift": false
      },
      {
        "name": "Standard ATV",
        "speedGround": 0.5,
        "speedWater": -0.25,
        "speedAir": -0.5,
        "speedGravity": 0,
        "acceleration": -1,
        "weight": 0.5,
        "handlingGround": -0.75,
        "handlingWater": -0.25,
        "handlingAir": -0.75,
        "handlingGravity": -0.5,
        "grip": 0.5,
        "miniturbo": -1,
        "insideDrift": false
      },
      {
        "name": "Wild Wiggler",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0.25,
        "acceleration": 0.25,
        "weight": -0.25,
        "handlingGround": 0.25,
        "handlingWater": 0.25,
        "handlingAir": 0,
        "handlingGravity": 0.25,
        "grip": 0.5,
        "miniturbo": 0.25,
        "insideDrift": false
      },
      {
        "name": "Teddy Buggy",
        "speedGround": -0.25,
        "speedWater": -0.25,
        "speedAir": 0.25,
        "speedGravity": 0,
        "acceleration": 0.25,
        "weight": 0,
        "handlingGround": 0.25,
        "handlingWater": 0,
        "handlingAir": 0.25,
        "handlingGravity": 0,
        "grip": 0,
        "miniturbo": 0.25,
        "insideDrift": false
      },
      {
        "name": "Bone Rattler",
        "speedGround": 0.25,
        "speedWater": 0.5,
        "speedAir": -0.75,
        "speedGravity": -0.25,
        "acceleration": -0.75,
        "weight": 0.5,
        "handlingGround": -0.5,
        "handlingWater": 0.75,
        "handlingAir": -0.5,
        "handlingGravity": -0.5,
        "grip": 0,
        "miniturbo": -0.5,
        "insideDrift": false
      },
      {
        "name": "Splat Buggy",
        "speedGround": 0.25,
        "speedWater": -0.25,
        "speedAir": 0,
        "speedGravity": 0.25,
        "acceleration": -0.25,
        "weight": -0.5,
        "handlingGround": -0.25,
        "handlingWater": 0.25,
        "handlingAir": -0.5,
        "handlingGravity": 0.5,
        "grip": 0,
        "miniturbo": -0.25,
        "insideDrift": false
      },
      {
        "name": "Inkstriker",
        "speedGround": 0,
        "speedWater": 0,
        "speedAir": 0.25,
        "speedGravity": 0.5,
        "acceleration": -0.25,
        "weight": 0.25,
        "handlingGround": -0.25,
        "handlingWater": 0,
        "handlingAir": -0.25,
        "handlingGravity": 0.25,
        "grip": 0.25,
        "miniturbo": 0,
        "insideDrift": false
      }
]