import { DriverModel } from "./types";

export const driverModels: DriverModel[] = [
    {
        "name": "LightDriverModel0",
        "size": "Small",
        "speedGround": 2.25,
        "speedWater": 2.5,
        "speedAir": 2.75,
        "speedGravity": 2,
        "acceleration": 4,
        "weight": 2,
        "handlingGround": 5,
        "handlingWater": 4.5,
        "handlingAir": 5,
        "handlingGravity": 5,
        "grip": 4.25,
        "miniturbo": 4
    },
    {
        "name": "LightDriverModel1",
        "size": "Small",
        "speedGround": 2.25,
        "speedWater": 2.5,
        "speedAir": 2.75,
        "speedGravity": 2,
        "acceleration": 4.25,
        "weight": 2,
        "handlingGround": 4.75,
        "handlingWater": 4.25,
        "handlingAir": 4.75,
        "handlingGravity": 4.75,
        "grip": 3.75,
        "miniturbo": 4
    },
    {
        "name": "LightDriverModel2",
        "size": "Small",
        "speedGround": 2.5,
        "speedWater": 2.75,
        "speedAir": 3,
        "speedGravity": 2.25,
        "acceleration": 4.25,
        "weight": 2.25,
        "handlingGround": 4.5,
        "handlingWater": 4,
        "handlingAir": 4.5,
        "handlingGravity": 4.5,
        "grip": 4,
        "miniturbo": 3.75
    },
    {
        "name": "LightDriverModel3",
        "size": "Small",
        "speedGround": 2.75,
        "speedWater": 3,
        "speedAir": 3.25,
        "speedGravity": 2.5,
        "acceleration": 4,
        "weight": 2.5,
        "handlingGround": 4.5,
        "handlingWater": 4,
        "handlingAir": 4.5,
        "handlingGravity": 4.5,
        "grip": 4.25,
        "miniturbo": 3.75
    },
    {
        "name": "LightDriverModel4",
        "size": "Small",
        "speedGround": 2.75,
        "speedWater": 3,
        "speedAir": 3.25,
        "speedGravity": 2.5,
        "acceleration": 4.25,
        "weight": 2.5,
        "handlingGround": 4.25,
        "handlingWater": 3.75,
        "handlingAir": 4.25,
        "handlingGravity": 4.25,
        "grip": 3.5,
        "miniturbo": 3.75
    },
    {
        "name": "LightDriverModel5",
        "size": "Small",
        "speedGround": 3,
        "speedWater": 3.25,
        "speedAir": 3.5,
        "speedGravity": 2.75,
        "acceleration": 4,
        "weight": 2.75,
        "handlingGround": 4.25,
        "handlingWater": 3.75,
        "handlingAir": 4.25,
        "handlingGravity": 4.25,
        "grip": 4,
        "miniturbo": 3.5
    },
    {
        "name": "MediumDriverModel0",
        "size": "Medium",
        "speedGround": 3.25,
        "speedWater": 3.5,
        "speedAir": 3.75,
        "speedGravity": 3,
        "acceleration": 4,
        "weight": 2.75,
        "handlingGround": 4,
        "handlingWater": 3.5,
        "handlingAir": 4,
        "handlingGravity": 4,
        "grip": 3.75,
        "miniturbo": 3.5
    },
    {
        "name": "MediumDriverModel1",
        "size": "Medium",
        "speedGround": 3.5,
        "speedWater": 3.75,
        "speedAir": 4,
        "speedGravity": 3.25,
        "acceleration": 3.75,
        "weight": 3,
        "handlingGround": 3.75,
        "handlingWater": 3.25,
        "handlingAir": 3.75,
        "handlingGravity": 3.75,
        "grip": 3.75,
        "miniturbo": 3.5
    },
    {
        "name": "MediumDriverModel2",
        "size": "Medium",
        "speedGround": 3.5,
        "speedWater": 3.75,
        "speedAir": 4,
        "speedGravity": 3.25,
        "acceleration": 3.75,
        "weight": 3.25,
        "handlingGround": 3.75,
        "handlingWater": 3.25,
        "handlingAir": 3.75,
        "handlingGravity": 3.75,
        "grip": 3.25,
        "miniturbo": 3.5
    },
    {
        "name": "MediumDriverModel3",
        "size": "Medium",
        "speedGround": 3.75,
        "speedWater": 4,
        "speedAir": 4.25,
        "speedGravity": 3.5,
        "acceleration": 3.5,
        "weight": 3.5,
        "handlingGround": 3.75,
        "handlingWater": 3.25,
        "handlingAir": 3.75,
        "handlingGravity": 3.75,
        "grip": 3.25,
        "miniturbo": 3.25
    },
    {
        "name": "MediumDriverModel4",
        "size": "Medium",
        "speedGround": 3.75,
        "speedWater": 4,
        "speedAir": 4.25,
        "speedGravity": 3.5,
        "acceleration": 3.5,
        "weight": 3.5,
        "handlingGround": 3.5,
        "handlingWater": 3,
        "handlingAir": 3.5,
        "handlingGravity": 3.5,
        "grip": 3.5,
        "miniturbo": 3.25
    },
    {
        "name": "HeavyDriverModel0",
        "size": "Heavy",
        "speedGround": 4,
        "speedWater": 4.25,
        "speedAir": 4.5,
        "speedGravity": 3.75,
        "acceleration": 3.25,
        "weight": 3.75,
        "handlingGround": 3.25,
        "handlingWater": 2.75,
        "handlingAir": 3.25,
        "handlingGravity": 3.25,
        "grip": 3.75,
        "miniturbo": 3.25
    },
    {
        "name": "HeavyDriverModel1",
        "size": "Heavy",
        "speedGround": 4.5,
        "speedWater": 4.75,
        "speedAir": 5,
        "speedGravity": 4.25,
        "acceleration": 3.25,
        "weight": 4,
        "handlingGround": 3,
        "handlingWater": 2.5,
        "handlingAir": 3,
        "handlingGravity": 3,
        "grip": 3,
        "miniturbo": 3
    },
    {
        "name": "HeavyDriverModel2",
        "size": "Heavy",
        "speedGround": 4.75,
        "speedWater": 5,
        "speedAir": 5.25,
        "speedGravity": 4.5,
        "acceleration": 3,
        "weight": 4.25,
        "handlingGround": 2.75,
        "handlingWater": 2.25,
        "handlingAir": 2.75,
        "handlingGravity": 2.75,
        "grip": 3.25,
        "miniturbo": 2.75
    },
    {
        "name": "HeavyDriverModel3",
        "size": "Heavy",
        "speedGround": 4.25,
        "speedWater": 4.5,
        "speedAir": 4.75,
        "speedGravity": 4,
        "acceleration": 3.25,
        "weight": 4.5,
        "handlingGround": 3.25,
        "handlingWater": 2.75,
        "handlingAir": 3.25,
        "handlingGravity": 3.25,
        "grip": 3.25,
        "miniturbo": 3
    },
    {
        "name": "HeavyDriverModel4",
        "size": "Heavy",
        "speedGround": 4.75,
        "speedWater": 5,
        "speedAir": 5.25,
        "speedGravity": 4.5,
        "acceleration": 3,
        "weight": 4.5,
        "handlingGround": 2.5,
        "handlingWater": 2,
        "handlingAir": 2.5,
        "handlingGravity": 2.5,
        "grip": 3,
        "miniturbo": 2.75
    }
]